export default {
    enroute: {
        airports: 'https://api.skylineflyleague.cn/efb-v2/enroute/nav/chunk-1.db',
        vors: 'https://api.skylineflyleague.cn/efb-v2/enroute/nav/chunk-2.db',
        ndbs: 'https://api.skylineflyleague.cn/efb-v2/enroute/nav/chunk-3.db',
        waypoints: 'https://api.skylineflyleague.cn/efb-v2/enroute/nav/chunk-4.db',
        airways: 'https://api.skylineflyleague.cn/efb-v2/enroute/nav/chunk-5.db',
        firs: 'https://api.skylineflyleague.cn/efb-v2/enroute/nav/chunk-6.db',
        grid: 'https://api.skylineflyleague.cn/efb-v2/enroute/nav/world-terrain.db',
        tilemap: 'https://api.skylineflyleague.cn/efb-v2/enroute/aip'
    },
    enrouteQuery: 'https://api.skylineflyleague.cn/efb-v2/enroute/query',
    enrouteSearch: 'https://api.skylineflyleague.cn/efb-v2/enroute/search',
    search:'https://api.skylineflyleague.cn/efb-v2/navdata/search',
    weather: 'https://api.skylineflyleague.cn/efb-v2/database/getWeather',
    notam: 'https://api.skylineflyleague.cn/efb-v2/database/getNOTAM',
    airport: 'https://api.skylineflyleague.cn/efb-v2/database/getAirport',
    jeppesenCharts: 'https://api.skylineflyleague.cn/efb-v2/charts/jeppesen/chartList',
    aipCharts: 'https://api.skylineflyleague.cn/efb-v2/charts/aip/chartList',
    jeppesenUrl: 'https://api.skylineflyleague.cn/efb-v2/charts/jeppesen/charturl',
    aipUrl: 'https://api.skylineflyleague.cn/efb-v2/charts/aip/charturl',
    airportCom:'https://api.skylineflyleague.cn/efb-v2/database/getCommunication',
    routeFinder:'https://api.skylineflyleague.cn/efb-v2/route/findRoute',
    parseSelfRoute:'https://api.skylineflyleague.cn/efb-v2/route/selfRoute',
    aircraftConfig: 'https://api.skylineflyleague.cn/efb-v2/database/getAircraftConfig',
    runways: 'https://api.skylineflyleague.cn/efb-v2/database/getRunways',
    procedure: 'https://api.skylineflyleague.cn/efb-v2/database/getProcedures',
    apps: 'https://api.skylineflyleague.cn/efb-v2/database/getAPPs',
    getFlights: 'https://api.skylineflyleague.cn/efb-v2/user/getFlights',
    updateFlights: 'https://api.skylineflyleague.cn/efb-v2/user/updateFlights',
    deleteFlights: 'https://api.skylineflyleague.cn/efb-v2/user/deleteFlight',
    uploadTempFlight: 'https://api.skylineflyleague.cn/efb-v2/user/upload',
    getTempFlight: 'https://api.skylineflyleague.cn/efb-v2/user/getTempFlights',
    deleteTempFlight: 'https://api.skylineflyleague.cn/efb-v2/user/unloadFlights',
    ownship: 'https://api.skylineflyleague.cn/map-api-v2/online',
    getPinboard: 'https://api.skylineflyleague.cn/efb-v2/user/getPinboard',
    uploadPinboard: 'https://api.skylineflyleague.cn/efb-v2/user/pinboardEvent',
    uploadWaypoint: 'https://api.skylineflyleague.cn/efb-v2/user/waypoint',
    navLink: 'https://api.skylineflyleague.cn/efb-v2/user/navlink',
    waypoint: 'https://api.skylineflyleague.cn/efb-v2/user/getWaypoint',
    login: 'https://api.skylineflyleague.cn/efb-v2/OAuth2.0/authorize',
    points: 'https://api.skylineflyleague.cn/efb-v2/user/useUserIntegral',
    uploadFile: 'https://api.skylineflyleague.cn/efb-v2/user/upload',
    weatherRadar: 'https://api.rainviewer.com/public/weather-maps.json',
    simbrief: 'https://www.simbrief.com/api/xml.fetcher.php',
    airac: 'https://api.skylineflyleague.cn/efb-v2/airac?get=current'
}